import React from "react";
import Head from "next/head";

const Header = React.lazy(() => import("child1/header"));
const Catalog = React.lazy(() => import("child2/catalo"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Shell App (3000)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>Header</Header>
      <h3>Shell App 3000</h3>
      <Catalog />
    </>
  );
}
